-- CREATE USER IF NOT EXISTS 'chef'@'localhost' IDENTIFIED BY 'cook123';
-- GRANT ALL PRIVILEGES ON recipeapp TO 'chef'@'localhost' WITH GRANT OPTION;

DROP DATABASE IF EXISTS recipeapp;
CREATE DATABASE recipeapp;
USE recipeapp;


CREATE TABLE recipe(
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100)
);

CREATE TABLE ingredient (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    UOM VARCHAR(50)
);

CREATE TABLE ri_rel (
    RecipeID INTEGER REFERENCES recipe(Id),
    IngredientId Integer REFERENCES ingredient(Id),
    PRIMARY KEY (RecipeID, IngredientId),
    Quantity INTEGER
);

-- Beispiel-Einfügungen für die 200 gängigsten Zutaten
INSERT INTO ingredient (name, uom) VALUES
('Salz', 'Prise'),
('Pfeffer', 'Prise'),
('Zucker', 'Teelöffel'),
('Olivenöl', 'Esslöffel'),
('Butter', 'Gramm'),
('Knoblauch', 'Zehe'),
('Zwiebeln', 'Stück'),
('Mehl', 'Tasse'),
('Milch', 'Liter'),
('Eier', 'Stück'),
('Tomaten', 'Stück'),
('Huhn', 'Gramm'),
('Rindfleisch', 'Gramm'),
('Schweinefleisch', 'Gramm'),
('Lachs', 'Gramm'),
('Thunfisch', 'Gramm'),
('Karotten', 'Stück'),
('Sellerie', 'Stange'),
('Brokkoli', 'Gramm'),
('Kartoffeln', 'Stück'),
('Paprika', 'Stück'),
('Gurken', 'Stück'),
('Salat', 'Kopf'),
('Spinat', 'Gramm'),
('Champignons', 'Gramm'),
('Käse', 'Gramm'),
('Reis', 'Tasse'),
('Pasta', 'Gramm'),
('Brot', 'Scheibe'),
('Rosmarin', 'Prise'),
('Oregano', 'Prise'),
('Basilikum', 'Prise'),
('Zitrone', 'Stück'),
('Limette', 'Stück'),
('Orangen', 'Stück'),
('Äpfel', 'Stück'),
('Banane', 'Stück'),
('Erdbeeren', 'Gramm'),
('Blaukäse', 'Gramm'),
('Gouda', 'Gramm'),
('Parmesan', 'Gramm'),
('Schlagsahne', 'Milliliter'),
('Joghurt', 'Milliliter'),
('Honig', 'Teelöffel'),
('Essig', 'Esslöffel'),
('Senf', 'Teelöffel'),
('Ketchup', 'Teelöffel'),
('Sojasauce', 'Teelöffel'),
('Kreuzkümmel', 'Teelöffel'),
('Currypulver', 'Teelöffel'),
('Chili', 'Teelöffel'),
('Schwarzer Tee', 'Gramm'),
('Kaffee', 'Gramm'),
('Wein', 'Milliliter'),
('Bier', 'Milliliter'),
('Zimt', 'Prise'),
('Vanille', 'Teelöffel'),
('Nelken', 'Prise'),
('Nussmus', 'Teelöffel'),
('Mandel', 'Gramm'),
('Walnuss', 'Gramm'),
('Pistazien', 'Gramm'),
('Schokolade', 'Gramm'),
('Vanillezucker', 'Teelöffel'),
('Kakaopulver', 'Teelöffel'),
('Puderzucker', 'Teelöffel'),
('Zitronenschale', 'Teelöffel'),
('Erdnussbutter', 'Teelöffel'),
('Marmelade', 'Teelöffel'),
('Worchester-Sauce', 'Teelöffel'),
('Rosenwasser', 'Teelöffel'),
('Kokosmilch', 'Milliliter'),
('Kokosraspeln', 'Gramm'),
('Avocado', 'Stück'),
('Rettich', 'Stück'),
('Koriander', 'Prise'),
('Lauch', 'Stange'),
('Petersilie', 'Prise'),
('Dill', 'Prise'),
('Dijon-Senf', 'Teelöffel'),
('Tabasco', 'Tropfen'),
('Majonäse', 'Teelöffel'),
('Sahnesauce', 'Teelöffel'),
('Sauerrahm', 'Teelöffel'),
('Apfelessig', 'Teelöffel'),
('Rotwein', 'Milliliter'),
('Weißwein', 'Milliliter'),
('Rum', 'Milliliter'),
('Whiskey', 'Milliliter'),
('Bourbon', 'Milliliter'),
('Wodka', 'Milliliter'),
('Gin', 'Milliliter'),
('Likör', 'Milliliter'),
('Sambuca', 'Milliliter'),
('Tequila', 'Milliliter'),
('Sake', 'Milliliter'),
('Cointreau', 'Milliliter'),
('Triple Sec', 'Milliliter'),
('Cognac', 'Milliliter'),
('Kirschlikör', 'Milliliter'),
('Amaretto', 'Milliliter'),
('Curacao', 'Milliliter'),
('Pfirsichschnaps', 'Milliliter'),
('Melonenlikör', 'Milliliter'),
('Erdbeerlikör', 'Milliliter'),
('Kokosnusslikör', 'Milliliter'),
('Schwarzer Johannisbeerlikör', 'Milliliter'),
('Anislikör', 'Milliliter'),
('Limettensaft', 'Milliliter'),
('Kirschsaft', 'Milliliter'),
('Grenadine', 'Teelöffel'),
('Zitronenlimonade', 'Milliliter'),
('Ginger Ale', 'Milliliter'),
('Tonic Water', 'Milliliter'),
('Club Soda', 'Milliliter'),
('Cola', 'Milliliter'),
('Orangensaft', 'Milliliter'),
('Cranberrysaft', 'Milliliter'),
('Tomatensaft', 'Milliliter'),
('Eistee', 'Milliliter'),
('Wasser', 'Milliliter'),
('Eiswürfel', 'Stück'),
('Salzlake', 'Teelöffel'),
('Gemüsebrühe', 'Liter'),
('Hühnerbrühe', 'Liter'),
('Fischsauce', 'Teelöffel'),
('Miso-Paste', 'Teelöffel'),
('Panko-Paniermehl', 'Gramm'),
('Zuckermais', 'Stück'),
('Schwarze Bohnen', 'Gramm'),
('Kidneybohnen', 'Gramm'),
('Erbsen', 'Gramm'),
('Linsen', 'Gramm'),
('Weiße Bohnen', 'Gramm'),
('Kichererbsen', 'Gramm'),
('Artischocken', 'Stück'),
('Herz von Palm', 'Stück'),
('Okra', 'Stück'),
('Bohnen', 'Stück'),
('Auberginen', 'Stück'),
('Sauerkraut', 'Gramm'),
('Avocadoöl', 'Teelöffel'),
('Rapsöl', 'Teelöffel'),
('Distelöl', 'Teelöffel'),
('Maisöl', 'Teelöffel'),
('Sonnenblumenöl', 'Teelöffel'),
('Sesamöl', 'Teelöffel'),
('Palmöl', 'Teelöffel'),
('Mandelöl', 'Teelöffel'),
('Walnussöl', 'Teelöffel'),
('Haselnussöl', 'Teelöffel'),
('Rüböl', 'Teelöffel'),
('Kartoffelöl', 'Teelöffel'),
('Kokosnussöl', 'Teelöffel'),
('Petersilienwurzel', 'Stück'),
('Kohlrabi', 'Stück'),
('Topinambur', 'Stück'),
('Rosenkohl', 'Stück'),
('Chicorée', 'Stück'),
('Endivie', 'Stück'),
('Mangold', 'Blatt'),
('Fenchel', 'Stück'),
('Radieschen', 'Stück'),
('Schnittlauch', 'Bund'),
('Kresse', 'Bund'),
('Basilikum', 'Bund'),
('Rosmarin', 'Zweig'),
('Thymian', 'Zweig'),
('Majoran', 'Zweig'),
('Petersilie', 'Bund'),
('Liebstöckel', 'Blatt'),
('Zitronengras', 'Stängel'),
('Lorbeerblatt', 'Blatt'),
('Korianderblätter', 'Bund'),
('Minze', 'Bund'),
('Kardamom', 'Kapsel'),
('Sternanis', 'Stern'),
('Kreuzkümmelsamen', 'Teelöffel'),
('Fenchelsamen', 'Teelöffel'),
('Koriandersamen', 'Teelöffel'),
('Senfsamen', 'Teelöffel'),
('Kurkuma', 'Teelöffel'),
('Piment', 'Teelöffel'),
('Majoran', 'Teelöffel'),
('Kümmel', 'Teelöffel'),
('Basilikum', 'Teelöffel'),
('Schnittlauch', 'Teelöffel'),
('Dill', 'Teelöffel'),
('Petersilie', 'Teelöffel'),
('Kerbel', 'Teelöffel'),
('Bohnenkraut', 'Teelöffel'),
('Wacholderbeeren', 'Teelöffel'),
('Estragon', 'Teelöffel'),
('Kreuzkümmelpulver', 'Teelöffel'),
('Paprikapulver', 'Teelöffel'),
('Chilipulver', 'Teelöffel'),
('Ingwerpulver', 'Teelöffel'),
('Zimtpulver', 'Teelöffel'),
('Muskatnuss', 'Prise'),
('Piment', 'Prise'),
('Nelkenpulver', 'Prise'),
('Currypulver', 'Teelöffel'),
('Vanilleextrakt', 'Tropfen'),
('Zitronenextrakt', 'Tropfen'),
('Orangenextrakt', 'Tropfen'),
('Mandelaroma', 'Tropfen'),
('Zitronenzeste', 'Teelöffel'),
('Orangenzeste', 'Teelöffel');


-- Beispiel-Einfügungen für 50 gängige Rezepte in Europa
INSERT INTO recipe (name) VALUES
('Paella'),
('Lasagne'),
('Fish and Chips'),
('Moussaka'),
('Wiener Schnitzel'),
('Ratatouille'),
('Gulaschsuppe'),
('Borschtsch'),
('Couscous'),
('Tzatziki'),
('Pierogi'),
('Haggis'),
('Köttbullar'),
('Tiramisu'),
('Sauerbraten'),
('Bouillabaisse'),
('Moules-frites'),
('Coq au Vin'),
('Goulash'),
("Shepherd's Pie"),
('Carbonara'),
('Sarma'),
('Baklava'),
('Rösti'),
('Kebab'),
('Sarma'),
('Tarte Tatin'),
('Plov'),
('Irish Stew'),
('Ceviche'),
('Linsensuppe'),
('Cordon Bleu'),
('Raclette'),
('Pilaf'),
('Gazpacho'),
('Baba Ganoush'),
('Maultaschen'),
('Bruschetta'),
('Spanakopita'),
('Wassail'),
('Himmel und Erde'),
('Paprikash'),
('Colcannon'),
('Karelian Pasties'),
('Pisto'),
('Kedgeree'),
('Makowiec'),
('Blini'),
('Tortilla Española');

INSERT INTO ri_rel (RecipeID, IngredientId) VALUES
(1,5),
(1,6);